# Generated by Django 4.0.1 on 2022-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', upload_to=''),
        ),
    ]
